# Generated by Django 4.0.3 on 2022-03-13 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('happy', 'Happy'), ('angry', 'Angry'), ('ashamed', 'Ashamed'), ('bored', 'Bored'), ('calm', 'Calm'), ('cold', 'Cold'), ('proud', 'Proud'), ('confused', 'Confused'), ('crazy', 'Crazy'), ('depressed', 'Depressed'), ('good', 'Good'), ('hopeful', 'Hopeful'), ('hungry', 'Hungry'), ('alone', 'Alone')], default='happy', max_length=10)),
                ('coin', models.PositiveBigIntegerField(default=0)),
                ('total_rank', models.PositiveBigIntegerField(default=0)),
                ('experience', models.PositiveBigIntegerField(default=0)),
                ('clan_name', models.CharField(default='None', max_length=50)),
                ('clan_position', models.CharField(choices=[('none', 'None'), ('leader', 'Leader'), ('co-leader', 'Co-leader'), ('member', 'Member')], default='none', max_length=10)),
                ('invite_code', models.CharField(max_length=10)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('in-game', 'In-Game'), ('pending', 'Pending'), ('deleted', 'Deleted')], default='in-game', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('card_type', models.CharField(choices=[('common', 'Common'), ('monster', 'Monster'), ('legendary', 'Legendary'), ('champion', 'Champion')], max_length=10)),
                ('stage', models.PositiveIntegerField(default=1)),
                ('max_power', models.PositiveBigIntegerField(default=0)),
                ('revive_time', models.DurationField()),
                ('image', models.ImageField(upload_to='cards/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Icons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='icons/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccountLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.PositiveIntegerField(default=1)),
                ('minimum', models.PositiveIntegerField(default=0)),
                ('maximum', models.PositiveIntegerField(default=50)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
            ],
        ),
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_year', models.CharField(blank=True, max_length=5, null=True)),
                ('gender', models.CharField(choices=[('none', 'None'), ('male', 'Male'), ('female', 'Female')], default='none', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
            ],
        ),
        migrations.CreateModel(
            name='AccountIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_type', models.CharField(choices=[('common', 'Common'), ('vip', 'Vip')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
                ('icon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.icons')),
            ],
        ),
        migrations.CreateModel(
            name='AccountCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.PositiveIntegerField(default=1)),
                ('power', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('basket', 'Basket'), ('mining', 'Mining'), ('attack-building', 'Attack-Building'), ('defense-building', 'Defense-Building'), ('store', 'Store')], max_length=20)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.cards')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='icon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.icons'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
