# Generated by Django 4.0.3 on 2022-03-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_cards_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcards',
            name='price',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
