# Generated by Django 4.0.3 on 2022-03-18 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_accountcards_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcards',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account'),
        ),
        migrations.AlterField(
            model_name='accountcards',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.cards'),
        ),
    ]
